#pragma once

#define IDI_APP_ICON 101
#define IDR_UPDATER_SCRIPT 102
#define IDR_LAUNCHER_INTEGRATION_PATCH 103
#define IDR_LAUNCHER_INTEGRATION_PACKAGE 104
#define IDR_LAUNCHER_INTEGRATION_INDEX 105
#define IDR_LAUNCHER_INTEGRATION_CLIENT 106
